version: '3.0'
services:
  db:
    container_name: trading_db
    image: postgres:14.6-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    networks:
      - custom

networks:
  custom:
    driver: bridge
