version: '3.7'
services:
  db:
    container_name: trading_db
    image: postgres:14.6-alpine
    restart: always
    env_file:
      - .env-prod
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    networks:
      - custom
  test_db:
    container_name: trading_db_test
    image: postgres:14.6-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD_TEST}
      POSTGRES_USER: ${DB_USER_TEST}
      POSTGRES_DB: ${DB_NAME_TEST}
    ports:
      - 6000:5432
    networks:
      - custom



  redis:
    image: redis:7
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370

  app:
    build:
      context: .
    env_file:
      - .env-prod
    container_name: fastapi_app
    command: sh app.sh
    ports:
      - 9999:8000
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
    env_file:
      - .env-prod
    container_name: celery_app
    command: sh celery.sh celery
    depends_on:
      - redis

  flower:
    build:
      context: .
    env_file:
      - .env-prod
    container_name: flower_app
    command: sh celery.sh flower
    depends_on:
      - redis
      - celery
    ports:
      - 8888:5555





networks:
  custom:
    driver: bridge
