"""add message model

Revision ID: 179cc0990a1f
Revises: 191ab4ed4da3
Create Date: 2023-04-10 21:08:50.182691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '179cc0990a1f'
down_revision = '191ab4ed4da3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'message',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'message',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
