"""add message model

Revision ID: 74253a14558f
Revises: 7b21a4ffa613
Create Date: 2023-04-10 16:53:25.192325

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '74253a14558f'
down_revision = '7b21a4ffa613'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('message', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    # ### end Alembic commands ###
