"""add operation

Revision ID: a801786bf3ae
Revises: 1448627e985e
Create Date: 2023-04-04 12:50:08.173057

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a801786bf3ae'
down_revision = '1448627e985e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('quantity', sa.String(), nullable=False),
                    sa.Column('figi', sa.String(), nullable=False),
                    sa.Column('instrument_type', sa.String(), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.Column('type', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
                    sa.Column('permissions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False,
                              nullable=True),
                    sa.PrimaryKeyConstraint('id', name='role_pkey')
                    )
    op.drop_table('operation')
    # ### end Alembic commands ###
