"""add message model

Revision ID: 98a717b1d8e0
Revises: 179cc0990a1f
Create Date: 2023-04-11 12:35:46.090868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98a717b1d8e0'
down_revision = '179cc0990a1f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
